### ISSUE TITLE
[Proposal] Use filebeat taking place of hekad

### ISSUE THREAD

**Issue by ericpai** [laincloud/rebellion#6]
Hekad is deprecated and not stable. We should use other log processing system to take place of hekad.

Fluentd is a lightwight and ruby-based log processing program. It's easy to install and extend.

**Comment by ericpai** [comment]
http://www.fluentd.org/

**Comment by rmrf** [comment]
Wish this happen ASAP!

**Comment by ericpai** [comment]
Now we will extend filebeat to collect logs. https://github.com/laincloud/beats
